import type { AnalyzedWaypoint } from "@/lib/types";

type WarningsPanelProps = {
  warnings: string[];
  waypoints: AnalyzedWaypoint[];
};

export function WarningsPanel({ warnings, waypoints }: WarningsPanelProps) {
  const criticalPoints = waypoints.filter(
    (waypoint) => waypoint.risk.level === "high" || waypoint.risk.level === "extreme"
  );

  return (
    <section className="panel p-6">
      <div className="mb-5">
        <h2 className="text-lg font-semibold text-storm-900">Warnings</h2>
        <p className="mt-1 text-sm text-storm-600">
          Highlights generated by the route parser and weather-risk model.
        </p>
      </div>

      <div className="grid gap-3">
        {warnings.length === 0 && criticalPoints.length === 0 ? (
          <div className="rounded-[1.5rem] bg-ridge-50 p-4 text-sm text-ridge-800">
            No parser or forecast warnings yet. Upload a GPX and run analysis to
            populate this panel.
          </div>
        ) : null}

        {warnings.map((warning) => (
          <div
            key={warning}
            className="rounded-[1.5rem] border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"
          >
            {warning}
          </div>
        ))}

        {criticalPoints.slice(0, 4).map((waypoint) => (
          <div
            key={waypoint.analysisSequence}
            className="rounded-[1.5rem] border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-900"
          >
            Day {waypoint.dayIndex}, km {waypoint.distanceFromStartKm.toFixed(1)} around{" "}
            {new Intl.DateTimeFormat(undefined, {
              dateStyle: "medium",
              timeStyle: "short",
            }).format(new Date(waypoint.etaIso))}
            : {waypoint.risk.reasons.join(", ")}
          </div>
        ))}
      </div>
    </section>
  );
}
